### ISSUE TITLE
Thoughts?

### ISSUE THREAD

**Issue by jlthibault** [theadamparker/BusFed-2014#120]
@theadamparker Contrary to what it seems, I'm not ACTUALLY trying to keep adding to our list, but we're getting close to the point where we can split hairs and get picky.

What do you think about this?

![screen shot 2015-04-05 at 12 38 31 am](https://cloud.githubusercontent.com/assets/5427577/6995787/21ae7bd0-db2c-11e4-8e42-ef02943881d0.png)

**Comment by theadamparker** [comment]
@jlthibault: I like it. Implementing!
