### ISSUE TITLE
Expenses pie chart needs to be broken into smaller categories.

### ISSUE THREAD

**Issue by theadamparker** [theadamparker/BusFed-2014#134]
This was mentioned on the call, but we don't know what the smaller categories are.

**Comment by jlthibault** [comment]
From Sarah:

Here's an updated revenue breakdown for the financials chart 
(you can leave the actual financial statement of activities the same):

Foundations: $671,350
Individuals: $141,186
Labor: $35,000
Businesses: $11,000
In-Kind Contributions: $5,617
Other: $1,719
