### ISSUE TITLE
Outstanding Questions for Bus

### ISSUE THREAD

**Issue by jlthibault** [theadamparker/BusFed-2014#135]
@theadamparker I'm collecting our open questions to send over to them, please add any outstanding from your side. I think we could ask for their feedback by email at this point when sending these q's over, unless you would rather do a call tomorrow night? 
1. What are the categories that they want expenses broken down into?
2. Matt's feedback noted incorporating the OF/BY/FOR tagline into the heading section somehow: how would they like to see that done?

**Comment by theadamparker** [comment]
@jlthibault No more questions from my end beyond their general feedback. I don't think it warrants a phone call.
