### ISSUE TITLE
Intro headline is misaligned in Firefox

### ISSUE THREAD

**Issue by theadamparker** [theadamparker/BusFed-2014#136]
The first line is misaligned with the rest of the text. Bug isn't visible in Chrome, but is in Firefox. 

![screen shot 2015-04-06 at 1 40 35 pm](https://cloud.githubusercontent.com/assets/2205158/7008633/96fd7f1c-dc62-11e4-9b93-d2e3850de892.png)

**Comment by jlthibault** [comment]
@theadamparker  grumble grumble not working. any ideas?

**Comment by theadamparker** [comment]
[This site](http://animalnewyork.com/) is doing it successfully. Maybe we can check out how they've accomplished it.
