### ISSUE TITLE
Content: On the NVRD section

### ISSUE THREAD

**Issue by theadamparker** [theadamparker/BusFed-2014#139]
From Henry:

> I love these changes! In the partner growth can you make the 2012 circle a bit smaller? I'm not sure the growth reads as doubling right now. But I really like the progress!

@jlthibault: Initially, I was skeptical about the accuracy of this graphic, but crunched the numbers and was surprised to see that it looked right. So I'd push back on Henry's request in favor of keeping things accurate. Thoughts?

**Comment by jlthibault** [comment]
used the same circles but different placement—let's see :)

**Comment by theadamparker** [comment]
@jlthibault I'll be surprised if this solution does the trick.

**Comment by theadamparker** [comment]
@jlthibault oh I see now. This change wasn't made when I commented. I think bottoms aligning them improves things.
