### ISSUE TITLE
Navbar bus: colored

### ISSUE THREAD

**Issue by theadamparker** [theadamparker/BusFed-2014#50]
The bus could be orange in you're in the top section.

**Comment by theadamparker** [comment]
@jlthibault This has been harder to do than expected. I found some fancy code that was supposed to make it happen, but I used said fancy code and nothing happened. Alternatively we could use a PNG to create an image mask, and change the background color. But I think there's a high risk for bugginess, and low payoff for success.

**Comment by jlthibault** [comment]
@theadamparker sounds like it's not worth it

**Comment by theadamparker** [comment]
Ok, incomplete but closing this issue.
