### ISSUE TITLE
Ticker

### ISSUE THREAD

**Issue by jlthibault** [theadamparker/BusFed-2014#74]
Make it text instead of a ticker.
Young leaders wording: working?
2014 young interns and fellows graduated (gone through program start to finish. Semester/Quarter or 10 week programs)

**Comment by jlthibault** [comment]
@theadamparker what do you think about this? I was thinking that it would play off the large images below nicely, but not sure if it would cause your eye to hop around too much. If you like it better than the ticker, could you code it in?
![screen shot 2015-04-04 at 12 59 28 am](https://cloud.githubusercontent.com/assets/5427577/6991485/e8236432-da65-11e4-8ebb-4ba1af4e3a65.png)

**Comment by theadamparker** [comment]
Looks great. Thumbs up.

**Comment by jlthibault** [comment]
AWESOME! looks great on mobile
