### ISSUE TITLE
work in subtitle or tagline to top frame ?

### ISSUE THREAD

**Issue by jlthibault** [theadamparker/BusFed-2014#92]
can we use the "that an organization OF young people, BY young people, and FOR all people...." to somewhere on the title screen?

**Comment by theadamparker** [comment]
@jlthibault I think we're going to need some more words than just these. Is this their mission statement? Where have these words appeared before, and can we fill in the blanks here?

**Comment by jlthibault** [comment]
@theadamparker i agree we don't have enough info from them yet, that's why this item isn't assigned. It was on Matt's feedback list though, so wanted to log the issue. Let's ask about it when we send over email to review
