### ISSUE TITLE
Redesign voter turnout infographic

### ISSUE THREAD

**Issue by jlthibault** [theadamparker/BusFed-2014#93]
NVRD total registrations: 154,500
number of field registrations = 81,601
number of online voter registrations = 72,899

**Comment by jlthibault** [comment]
add the words "groups" or "orgs" to partners. Add how many voters we registered.

**Comment by jlthibault** [comment]
@theadamparker whaddya think?

**Comment by theadamparker** [comment]
@jlthibault: Looks great.
